# Pepper for password hashing
# Set this once! Don't change afterwards!
pepper: "5!yLZ;d:d"

# Connection to mysql database
# Note: 'unix_socket' will take advantage over 'host'
database:
        name: "dailymood"
        user: "dailymood"
        password: ""
        # Unix:
        unix_socket: "/var/run/mysqld/mysqld.sock"
        # Remote:
        host: "localhost"
