# Pepper for password hashing
# Set this once! Don't change afterwards!
pepper: "5!yLZ;d:d"

# Connection to mysql database
database:
	host: "localhost"
	name: "dailymood"
	user: "root"
	password: ""